name: meatingless
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  badges: ^3.1.1
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_floating_bottom_bar: ^1.1.0
  flutter_hooks: ^0.20.5
  flutter_keyboard_visibility: ^5.4.1
  flutter_launcher_icons: ^0.13.1
  flutter_riverpod: ^2.3.6
  flutter_stripe: ^9.5.0+1
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  geocoding: ^2.1.1
  geolocator: ^10.1.1
  go_router: ^8.0.3
  google_fonts: ^5.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  hooks_riverpod: ^2.4.10
  json_annotation: ^4.8.1
  lottie: ^2.4.0
  numeral: ^2.0.1
  payu:
    git: 
      url: https://github.com/PayU-EMEA/PayU-Flutter.git
      path: payu


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/icons/
    - .env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icon/food_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true

