name: meatingless
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_floating_bottom_bar: ^1.1.0
  flutter_riverpod: ^2.3.6
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  go_router: ^8.0.3
  google_fonts: ^5.0.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/icons/


